import { describe, it, expect } from "bun:test"
import { parseSlashCommand, buildHelpText } from "../src/commands.js"
import type { Strings } from "../src/i18n/strings.js"

function stubStrings(overrides?: Partial<Strings>): Strings {
  const s: Strings = {
    placeholder: '',
    queued: () => '',
    processing: '',
    pasteSummary: () => '',
    allow: '',
    alwaysAllow: '',
    deny: '',
    permissionTitle: '',
    requestsToExecute: '',
    parameters: () => '',
    permissionHint: '',
    thinking: '',
    toolUse: '',
    you: '',
    assistant: '',
    reply: '',
    ctrlO: '',
    thinkingDots: '',
    roleWorker: '',
    roleSupervisor: '',
    roleUnknown: '',
    inputTokens: '',
    outputTokens: '',
    cacheHit: '',
    sessions: '',
    sessionHint: '',
    loading: '',
    error: '',
    noSessions: '',
    msgs: () => '',
    modelSettings: '',
    current: '',
    enterApiKey: () => '',
    escToGoBack: '',
    pressEToEdit: '',
    pressDToDelete: '',
    keySourceEnv: '',
    keySourceFile: '',
    keySourceDefault: '',
    configured: '',
    yourApiKey: '',
    confirmDelete: '',
    pressYToConfirm: '',
    updateKey: '',
    apiKeyMasked: () => '',
    cmdExit: '',
    cmdHelp: '',
    cmdModel: '',
    cmdSessions: '',
    cmdAgent: '',
    cmdSkill: '',
    cmdLang: '',
    cmdStatus: '',
    cmdContext: '',
    pressCtrlC: '',
    shuttingDown: '',
    loadedSkills: () => '',
    failedLoadSkills: () => '',
    switchedTo: () => '',
    switchedModel: () => '',
    switchedLang: () => '',
    resumedSession: () => '',
    writing: '',
    aborted: '',
    tps: () => '',
    linesDropped: () => '',
    truncatedByEsc: '',
    rejected: '',
    exitCode: () => '',
    cmdAutocompleteHint: '',
    searchHint: '',
    unknownError: '',
    unknownWarning: '',
    unknown: '',
    pendingTasks: '',
    plural: () => '',
    helpTitle: '',
    helpAgents: '',
    helpCurrent: '',
    helpDeprecatedAgentNote: '',
    cmdTheme: '',
    cmdThinking: '',
    cmdWorkflow: '',
    cmdTalk: '',
    cmdGoal: '',
    cmdGoalSet: '',
    cmdGoalEdit: '',
    cmdGoalPause: '',
    cmdGoalResume: '',
    cmdGoalClear: '',
    cmdGoalBudget: '',
    cmdGoalNoBudget: '',
    failedLoadStatus: '',
    thinkingModeSet: () => '',
    thinkingModeCurrent: () => '',
    harnessStatus: () => '',
    harnessSetSession: () => '',
    harnessSetProject: () => '',
    harnessProjectUsage: '',
    workflowInstructionQueued: () => '',
    inputTargetSwitched: () => '',
    goalSet: () => '',
    goalReplaced: () => '',
    goalUpdated: () => '',
    goalNoActive: '',
    goalNoActiveToEdit: '',
    goalPause: '',
    goalResume: '',
    goalClear: '',
    goalInvalidBudget: '',
    goalBudgetSet: () => '',
    goalBudgetRemoved: '',
    goalStatusLine: () => '',
    goalOnlyLoop: '',
    goalNoBudgetSet: '',
    goalUsage: '',
    welcomeTagline: '',
    welcomePanelAgent: '',
    welcomePanelComponents: '',
    welcomeThinking: '',
    welcomeContext: '',
    welcomeSubagent: '',
    welcomeProvider: '',
    welcomeSkills: '',
    welcomeMcp: '',
    welcomeDiagnostics: () => '',
    welcomeDiagnosticsLabel: '',
    welcomeHelpHint: '',
    welcomeLangHint: '',
    contextModeTrim: '',
    contextModeCompact: '',
    modalEscClose: '',
    selectHint: '',
    loadingSkills: '',
    skillsAvailable: () => '',
    noSkillsFound: '',
    skillEnabled: () => '',
    skillDisabled: () => '',
    skillNoDescription: '',
    skillFooterHint: '',
    contextLoading: '',
    contextLoaded: '',
    contextSaved: '',
    contextReducing: '',
    contextSubtitle: () => '',
    contextModeDescription: '',
    contextTriggerDescription: () => '',
    contextTargetDescription: () => '',
    contextRunNow: '',
    contextRunDescription: '',
    contextFooterHint: '',
    contextRunResult: () => '',
    permissionRead: '',
    permissionEdit: '',
    permissionExecute: '',
    permissionDirectory: '',
    permissionFetch: '',
    permissionSearch: '',
    permissionAgent: '',
    permissionAllowOnce: '',
    permissionAlwaysAllow: '',
    permissionReject: '',
    permissionToolWants: '',
    permissionPatterns: '',
    permissionSuggested: '',
    permissionEnterConfirm: '',
    permissionEscReject: '',
    permissionRejectTitle: '',
    permissionToolDenied: '',
    permissionTypeMessage: '',
    permissionEnterSubmit: '',
    permissionEscCancel: '',
    permissionUpDownSelect: '',
    permissionAlwaysTitle: '',
    permissionAlwaysAutoApproved: '',
    questionSummary: '',
    questionNoAnswer: '',
    questionSubmitting: '',
    questionConfirmAnswers: '',
    questionTypeYourOwn: '',
    questionTypeAnswer: '',
    statusSectionStatus: '',
    statusSectionContext: '',
    statusSectionStats: '',
    statusSectionSessionWriter: '',
    statusYes: '',
    statusNo: '',
    workflowPhaseAnalyse: '',
    workflowPhaseDo: '',
    workflowPhaseReport: '',
    workflowPhaseCheck: '',
    workflowPhaseContinue: '',
    workflowPhaseRevise: '',
    workflowPhaseApprove: '',
    workflowPhaseBlocked: '',
    workflowPhaseAskUser: '',
    workflowLifecycleAwaitingGoal: '',
    workflowLifecycleRunning: '',
    workflowLifecycleWaiting: '',
    workflowLifecycleBlocked: '',
    workflowLifecycleCompleted: '',
    workflowLifecycleFailed: '',
    workflowRoleIdle: '',
    workflowRoleAnalyse: '',
    workflowRoleDo: '',
    workflowRoleReport: '',
    workflowRoleWait: '',
    workflowRoleBlocked: '',
    workflowModeAlone: '',
    workflowModeSubagent: '',
    workflowModeLoop: '',
    workflowAwaitingGoal: '',
    workflowBlockedMsg: '',
    workflowAlreadyRunning: '',
    workflowModeChanged: () => '',
    workflowLoopStarted: '',
    agentStatusQueued: '',
    agentStatusStarting: '',
    agentStatusRunning: '',
    agentStatusPermission: '',
    agentStatusAnswer: '',
    agentStatusReview: '',
    agentStatusVerifying: '',
    agentStatusPaused: '',
    agentStatusCompleted: '',
    agentStatusFailed: '',
    agentStatusCancelled: '',
    agentStatusIdle: '',
    agentGroupRunning: () => '',
    agentGroupCompleted: () => '',
    agentGroupFailed: () => '',
    agentGroupNoWorkers: '',
    agentGroupWorkersIdle: () => '',
    workerPanelTitle: '',
    workerPanelTotal: () => '',
    workerPanelOutputFocused: '',
    workerPanelList: '',
    workerPanelNoActive: '',
    workerPanelNoOutput: '',
    workerPanelNotFound: '',
    workerPanelOutput: () => '',
    workerPanelSelectHint: '',
    workerPanelEscBack: '',
    workerPanelNavigate: '',
    workerTaskDone: '',
    workerTaskError: '',
    workerTaskIdle: '',
    virtualizedNoMessages: '',
    virtualizedScrollToBottom: '',
    virtualizedBottom: '',
    contextModeRowLabel: '',
    contextTriggerRowLabel: '',
    contextTargetRowLabel: '',
    contextRunRowLabel: '',
    modelCustomConfigure: '',
    modelCustomBaseUrl: '',
    modelCustomModel: '',
    modelCustomPlaceholder: '',
    harnessStrictDesc: '',
    harnessNormalDesc: '',
    harnessLooseDesc: '',
    harnessSetTo: () => '',
    harnessProjectSet: () => '',
    harnessFooter: '',
    workflowMenuAlone: () => '',
    workflowMenuSubagent: () => '',
    workflowMenuLoop: () => '',
    workflowInterruptRunning: '',
    agentMenuTitle: () => '',
    agentMenuSubtitle: () => '',
    searchNoMatch: '',
    customProviderName: '',
    ...overrides,
  }
  return s
}

describe("Slash Command /status", () => {
  it("parseSlashCommand recognizes /status", () => {
    const result = parseSlashCommand("/status")
    expect(result).toEqual({ name: "status" })
  })

  it("parseSlashCommand recognizes /status with whitespace", () => {
    const result = parseSlashCommand("  /status  ")
    expect(result).toEqual({ name: "status" })
  })

  it("buildHelpText includes /status", () => {
    const helpText = buildHelpText("build", stubStrings({
      cmdExit: "Exit the program",
      cmdHelp: "Show this help",
      cmdModel: "Switch model",
      cmdSessions: "List sessions",
      cmdAgent: "Switch agent",
      cmdSkill: "List skills",
      cmdLang: "Switch language",
      cmdStatus: "Show status",
    }))
    expect(helpText).toContain("/status")
    expect(helpText).toContain("Show status")
  })
})
